Try ngihtly stuff

diff --git a/.github/workflows/steam.yml b/.github/workflows/steam.yml
--- a/.github/workflows/steam.yml
+++ b/.github/workflows/steam.yml
@@ -4,6 +4,14 @@ on:
   release:
     types:
     - published
+  workflow_dispatch:
+  # workflow_dispatch:
+  #   inputs:
+  #     tag:
+  #       description: 'Release to upload'
+  #       required: true
+  schedule:
+    - cron: '0 0 * * *'
 
 jobs:
   upload:
@@ -17,7 +25,15 @@ jobs:
         path: "source"
 
     - name: Download and extract release assets
+      if: github.event_name == 'release'
       run: |
+        DESC=${{ github.event.release.tag_name }}
+        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
+          BRANCH="beta_staging"
+        else
+          BRANCH="staging"
+        fi
+        
         curl -s "${{ github.event.release.assets_url }}" -o assets.json
         WIN_ASSET_URL=$(jq -r '.[] | select(.name|test(".*x64.zip")) .browser_download_url' assets.json)
         MAC_ASSET_URL=$(jq -r '.[] | select(.name|test(".*.dmg")) .browser_download_url' assets.json)
@@ -50,6 +66,49 @@ jobs:
         )
         
         rm windows.zip mac.dmg
+    
+    - name: Download and extract nightly build
+      if: github.event_name != 'release'
+      run: |
+        BRANCH="nightly"
+        # don't hardcode this once this goes live
+        curl -s "https://api.github.com/repos/obsproject/obs-studio/actions/workflows/583765/runs?per_page=10&event=push&status=completed&branch=master" -o builds.json
+        ARTIFACTS_URL=$(jq -r '.workflow_runs[] | select(.conclusion == "success") .artifacts_url' builds.json | head -n1)
+        DESC="nightly-g$(jq -r '.workflow_runs[] | select(.conclusion == "success") .head_sha' builds.json | head -n1 | cut -c1-7)"
+        
+        curl -s $ARTIFACTS_URL -o artifacts.json
+        WIN_ARTIFACT_ID=$(jq -r '.artifacts[] | select(.name|test(".*win64")) .id' artifacts.json)
+        MAC_ARTIFACT_ID=$(jq -r '.artifacts[] | select(.name|test(".*dmg")) .id' artifacts.json)
+        
+        wget "https://obsbot.rodney.io/artifacts/${WIN_ARTIFACT_ID}" -O windows.zip
+        wget "https://obsbot.rodney.io/artifacts/${MAC_ARTIFACT_ID}" -O mac.dmg.zip
+        
+        mkdir steam
+        (
+          cd steam
+          echo "::group::Extract Win64"
+          mkdir steam-windows
+          (
+            cd steam-windows
+            unzip ../../windows.zip
+          )
+          echo "::endgroup::"
+          
+          echo "::group::Extract macOS"
+          # This is crap and should be replaced before going into production.
+          cp ../source/CI/steam/7zzs .
+          chmod +x 7zzs
+          
+          echo "Extracting DMG and moving over .app ..."
+          mkdir steam-macos
+          # ignore exit code from 7zip
+          unzip ../mac.dmg.zip
+          ./7zzs x *.dmg -otmp || true
+          mv tmp/*/OBS.app steam-macos
+          rm -rf tmp/ *.dmg
+          echo "::endgroup::"
+        )
+        rm windows.zip mac.dmg.zip
 
     - name: Setup steamcmd
       uses: CyberAndrii/setup-steamcmd@v1
@@ -77,14 +136,7 @@ jobs:
         echo "::endgroup::"
 
         echo "::group::Preparing build file"
-
-        if [ "${{ github.event.release.prerelease }}" = "true" ]; then
-          BRANCH="beta"
-        else
-          BRANCH="staging"
-        fi
-
-        sed 's/@@DESC@@/${{ github.event.release.tag_name }}/;s/@@BRANCH@@/'${BRANCH}'/' ../source/CI/steam/obs_build.vdf > release.vdf
+        sed 's/@@DESC@@/${DESC}/;s/@@BRANCH@@/'${BRANCH}'/' ../source/CI/steam/obs_build.vdf > release.vdf
         echo "::endgroup::"
 
         echo "::group::Upload to Steam"
